# IOS


trigger:
- OneApp

pool:
  vmImage: 'macos-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy images'
  inputs:
    SourceFolder: './images/oneapp'
    Contents: '**'
    TargetFolder: './resources'
    CleanTargetFolder: true

- task: Npm@1
  displayName: 'npm ionic'
  inputs:
    command: custom
    workingDir: ''
    verbose: false
    customCommand: 'install -g @ionic/cli native-run cordova-res'

- task: Npm@1
  displayName: 'npm capacitor'
  inputs:
    command: custom
    workingDir: ''
    verbose: false
    customCommand: 'cache verify npm install @capacitor/cli'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: ''
    verbose: false

- task: Npm@1
  displayName: 'Creating resources'
  inputs:
    command: 'custom'
    workingDir: ''
    verbose: false
    customCommand: 'run resources'
    
- task: Bash@3
  displayName: 'Build'
  inputs:
    targetType: 'inline'
    script: 'npx ng build --configuration=oneapp'

- task: CocoaPods@0
  inputs:
    workingDirectory: 'ios/App'
    forceRepoUpdate: true
  
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'ios_distribution.p12'
    certPwd: 'onebeleza'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'onebelezaapp.mobileprovision'
    
- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 
    xcWorkspacePath: '**/App.xcworkspace'
    scheme: 'App'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    workingDirectory: ''



- task: CopyFiles@2
  inputs:
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactStagingDirectory)'
    OverWrite: true
    flattenFolders: true
   
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'