# Android

trigger:
- OneApp

pool:
  vmImage: 'macos-latest'

variables:
  - group: app-one

steps:
- task: replacetokens@3
  inputs:
    targetFiles: '**/environment.prod.ts'
    encoding: 'auto'
    writeBOM: false
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: CopyFiles@2
  displayName: 'Copy images'
  inputs:
    SourceFolder: './images/oneapp'
    Contents: '**'
    TargetFolder: './resources'
    CleanTargetFolder: true

- task: Npm@1
  displayName: 'npm ionic'
  inputs:
    command: custom
    workingDir: ''
    verbose: false
    customCommand: 'install -g @ionic/cli native-run cordova-res capacitor resources'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: ''
    verbose: false


- task: CmdLine@2
  inputs:
    script: 'ionic cordova resources'
    
- task: CmdLine@2
  inputs:
    script: 'ionic build --configuration=oneapp'

- task: CmdLine@2
  displayName: 'capacitor update'
  inputs:
    script: 'npx ionic capacitor update android'

- task: CmdLine@2
  displayName: 'capacitor copy'
  inputs:
    script: 'npx ionic capacitor copy android'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'android/gradlew'
    workingDirectory: 'android/'
    gradleOptions: '-Xmx3072m'
    jdkVersionOption: 1.11
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) **/*.apk'
  inputs:
    apkFiles: 'android/app/build/outputs/apk/release/*.apk'
    apksignerKeystoreFile: $(keystoreFileName)
    apksignerKeystorePassword: $(keystorePassword)
    apksignerKeystoreAlias: $(keyAlias)
    apksignerKeyPassword: $(keyPassword)
    zipalign: false

- task: CopyFiles@2
  inputs:
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

    
    
#Todo: Publicar na googleplay
# - task: GooglePlayRelease@3
#   inputs:
#     serviceConnection: 'Conect google play'
#     serviceAccountKey: '-----BEGIN PRIVATE KEY-----\n ... \n-----END PRIVATE KEY-----\n'
#     apkFile: 'android/app/build/outputs/apk/release/app-release-unsigned.apk'
#     track: 'alpha'