# Azure

trigger:
 - Exclusivo

pool:
  vmImage: 'macos-latest'

steps:
- task: replacetokens@3
  inputs:
    targetFiles: '**/environment.prod.ts'
    encoding: 'auto'
    writeBOM: false
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- task: CopyFiles@2
  displayName: 'Copy images'
  inputs:
    SourceFolder: './images/exclusivo'
    Contents: '**'
    TargetFolder: './resources'
    CleanTargetFolder: true

- task: Npm@1
  displayName: 'npm ionic'
  inputs:
    command: custom
    workingDir: ''
    verbose: false
    customCommand: 'install -g @ionic/cli native-run cordova-res'

- task: Npm@1
  displayName: 'npm capacitor'
  inputs:
    command: custom
    workingDir: ''
    verbose: false
    customCommand: 'install @capacitor/cli'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: ''
    verbose: false

- task: Npm@1
  displayName: 'Creating resources'
  inputs:
    command: 'custom'
    workingDir: ''
    verbose: false
    customCommand: 'run resources'
    
- task: Bash@3
  displayName: 'Build'
  inputs:
    targetType: 'inline'
    script: 'npx ng build --configuration=exclusivo'

- task: DeleteFiles@1
  inputs:
    Contents: '*/web.config'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/www'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Gerando arquivo .zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Gerando artefato'  
